title: numenichal
description: A website for vulgarization of numerical methods in engineering mechanics
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
permissions:
  contents: read
  pages: write
  id-token: write

logo: "/assets/images/numenichal_logo.png"
favicon_ico: "/assets/images/numenichal_ico.ico"

nav_enabled: true

color_scheme: dark

ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true